fix(ctrl): removed redis connection
cyclops-ui/cyclops pull request #223
Opened 2024-04-22 18:08 UTC by hanshal101

Fixes #195 
Closes #195 

## Description
This PR removes the Redis Connection in the `cyclops-ctrl` .
First (after depreciation) we could see the redis connection error in the console.  But after this PR you wont

2024-04-22 19:50 UTC, petar-cvit requested changes

2024-04-22 19:50 UTC, petar-cvit commented on cyclops-ctrl/internal/handler/handler.go
Can you also remove it from line 41 and 42 where its passed to templatesController and moduleController?
```
templatesController := controller.NewTemplatesController(h.templatesStorage, h.templatesRepo, h.k8sClient)
```
Feel free to delete anything that uses `templatesStorage`. If an endpoint relies on that structure, you can remove it. If you are not sure if you should remove it or not, feel free to ask, but anything using it can be deleted

2024-04-23 14:15 UTC, hanshal101 commented
Here you go.

2024-04-23 15:04 UTC, petar-cvit requested changes
You will also need to delete [this folder](https://github.com/cyclops-ui/cyclops/tree/main/cyclops-ctrl/internal/storage/templates), which implements `templates.Storage` and all occurrences of it.
It's the old way of storing templates, so we can get rid of it. I believe there are still some endpoints using that struct. You can delete those as well

2024-04-23 15:06 UTC, hanshal101 commented
yup I actually thought of removing this qt first and then resolve all the errors. But I thought this folder might have some exports in other part of the code base. Well will do👍

2024-04-24 09:23 UTC, petar-cvit requested changes

2024-04-24 09:23 UTC, petar-cvit commented on cyclops-ctrl/internal/controller/templates.go
You will need to restore this file since some of the endpoints are still used. Only the ones using `c.templates` can be removed, but others need to be here.

2024-04-24 09:23 UTC, petar-cvit commented on cyclops-ctrl/internal/controller/templates.go
> -func (c *Templates) StoreConfiguration(ctx *gin.Context) {
You can delete this one since it depends on c.templates

2024-04-24 09:23 UTC, petar-cvit commented on cyclops-ctrl/internal/controller/templates.go
> -func (c *Templates) GetTemplate(ctx *gin.Context) {
We need to keep this one since it uses only c.templatesRepo and is currently used for fetching templates

2024-04-24 09:23 UTC, petar-cvit commented on cyclops-ctrl/internal/controller/templates.go
I left some examples below on which methods are used and which are not

2024-04-24 16:12 UTC, merged