Sorted fields from values.schema.json
cyclops-ui/cyclops pull request #230
Opened 2024-04-27 15:39 UTC by RohanMishra315

Issue: #228

1. Sorted the fields from values.schema.json into the alphabetical form when the order is not provided
2.  When order is provided , the defined fields will come in order first and then the sorted fields.

2024-04-28 17:10 UTC, petar-cvit requested changes
Thanks @RohanMishra315 for the PR. I left a comment on the sorting logic

2024-04-28 17:10 UTC, petar-cvit commented on cyclops-ctrl/internal/mapper/helm.go
> +        })
Your solution works when the order is provided for all fields or not provided at all, but it doesn't work when 3/6 fields have the order defined. You can check the issue for further explanation of such a case.
I tried it with the following template, and I got the order from the picture.
```
repo: https://github.com/cyclops-ui/templates
path: demo-extended
version: field-alphabetical-sort
```
<img width="894" alt="Screenshot 2024-04-28 at 19 07 10" src="https://github.com/cyclops-ui/cyclops/assets/72022639/0f7893e9-52ff-4c5a-a834-2680e7bc46e9">

2024-05-13 13:39 UTC, RohanMishra315 commented
// Separate fields with order and without order
        var orderedFields []models.Field
        var unorderedFields []models.Field

        for _, field := range fields {
            if idx, ok := ordersMap[field.Name]; ok {
                orderedFields = append(orderedFields, models.FieldWithOrder{Field: field, OrderIndex: idx})
            } else {
                unorderedFields = append(unorderedFields, field)
            }
        }

        // Sort fields with order based on the order index
        sort.Slice(orderedFields, func(i, j int) bool {
            return orderedFields[i].OrderIndex < orderedFields[j].OrderIndex
        })

        // Reconstruct the sorted fields slice
        sortedFields := make([]models.Field, 0, len(fields))
        for _, field := range orderedFields {
            sortedFields = append(sortedFields, field.Field)
        }
        sortedFields = append(sortedFields, unorderedFields...)

        fields = sortedFields
    }

    return fields
}
I think this would work  I first separate the fields into two groups: those with a defined order and those without. We then sort the fields with a defined order based on the provided order index. Finally, we reconstruct the sorted fields slice by appending the ordered fields followed by the unordered fields. This approach ensures that fields with a defined order are prioritized and appear before the alphabetically sorted ones, addressing the issue you encountered where only a subset of fields had a defined order.

2024-05-13 13:42 UTC, hanshal101 commented
Hey can you edit the comment again I think there's some mistake

2024-05-13 15:52 UTC, petar-cvit commented
Sounds good to me. The only thing I wouldn't do is introduce a new struct, `FieldWithOrder`. Instead, you can still sort them like this:
```go
sort.Slice(fields, func(i, j int) bool {
	return ordersMap[fields[i].Name] < ordersMap[fields[j].Name]
})
```

2024-05-13 15:53 UTC, petar-cvit commented
@RohanMishra315 feel free to update the PR with those changes

2024-05-15 15:46 UTC, petar-cvit requested changes

2024-05-15 15:46 UTC, petar-cvit commented on cyclops-ctrl/internal/mapper/helm.go
> +    } else {
You dont need this part. The code in the else statement should handle it.

2024-05-15 16:38 UTC, petar-cvit requested changes

2024-05-15 16:38 UTC, petar-cvit commented on cyclops-ctrl/internal/mapper/helm.go
>  }
You closed the function and returned after closing it

2024-05-16 08:24 UTC, petar-cvit approved these changes
Thanks @RohanMishra315!

2024-05-16 08:25 UTC, merged