fix:(#368) Removed the third unnecessary status
cyclops-ui/cyclops pull request #392
Opened 2024-07-02 17:34 UTC by tanbirali

closes #368 

## 📑 Description
The third status was unnecessary under deployments and hence removed.
## ✅ Checks

- [x] I have performed a self-review of my code

## ℹ Additional context
Here is an screenshot of the changes 
![image](https://github.com/cyclops-ui/cyclops/assets/124070023/502c5696-e873-4d12-843c-ebb1a6333240)

2024-07-02 18:29 UTC, petar-cvit requested changes

2024-07-02 18:29 UTC, petar-cvit commented on cyclops-ui/src/components/pages/ModuleDetails.tsx
> -              {statusIcon}
Can you also remove the code that calculates the `statusIcon`

2024-07-03 08:12 UTC, tanbirali commented
```
      statusIcon = (
        <CheckCircleTwoTone
          style={{ verticalAlign: "middle" }}
          twoToneColor={"#52c41a"}
        />
      );
 ```
@petar-cvit  do you want me to delete this, As far as I understand the statusIcon variable is responsible for the status now, third one was unnecessary so it was removed but the other two are coming from the same variable is it necessary to remove the variable itself

2024-07-03 12:57 UTC, petar-cvit commented
There are two `statusIcon` variables, of which one is used in the header, and the other is used inside the collapse body. You need to delete the one on line 373 and remove its calculation from lines 472 to 488

2024-07-05 10:23 UTC, petar-cvit approved these changes
@tanbirali thanks, thats it 🧡

2024-07-05 10:24 UTC, merged