disable telemetry with init
cyclops-ui/cyclops pull request #412
Opened 2024-07-13 11:43 UTC by thebigbone

closes #364 

## 📑 Description
added a telemetry flag which will disable the telemetry

## ✅ Checks
- [ ] I have updated the documentation as required
- [x] I have performed a self-review of my code

2024-07-16 14:14 UTC, petar-cvit requested changes
Thanks @thebigbone, left a couple of comments

2024-07-16 14:14 UTC, petar-cvit commented on cyctl/cmd/apply.go
> +					if appLabel == "cyclops-ctrl" {
Can we check for cyclops controller deployment by checking the name? Also, you can check for all of those in the same if statement
```suggestion
		if telemetry && obj.GetKind() == "Deployment" && obj.GetName() == "cyclops-ctrl" {
```

2024-07-16 14:14 UTC, petar-cvit commented on cyctl/cmd/apply.go
> +						err = doServerSideApply(context.TODO(), config, obj)
Are you first deploying the controller without telemetry and then updating it? I would prefer if just alter the object and then call the `doServerSideApply` with it

2024-07-16 14:14 UTC, petar-cvit commented on cyctl/cmd/apply.go
> +	applyCmd.Flags().BoolP("telemetry", "t", false, "disable telemetry")
Can we rename the flag to `disable-telemetry` and update the usage string to something like `disable emitting telemetry metrics from cyclops controller`

2024-07-17 06:31 UTC, thebigbone commented
done

2024-07-17 10:34 UTC, petar-cvit requested changes

2024-07-17 10:34 UTC, petar-cvit commented on cyctl/cmd/apply.go
> +		telemetry, _ := cmd.Flags().GetBool("disable-telemetry")
Can you handle the error and rename the variable to `disableTelemetry`?
```suggestion
		disableTelemetry, err := cmd.Flags().GetBool("disable-telemetry")
		if err != nil {
			log.Fatal(err)
		}
```

2024-07-17 10:59 UTC, thebigbone commented
done

2024-07-17 11:47 UTC, petar-cvit requested changes

2024-07-17 11:47 UTC, petar-cvit commented on cyctl/cmd/apply.go
> +func applyYaml(yamlFile []byte, config *rest.Config, telemetry bool) error {
Can you also rename this one?

2024-07-17 12:04 UTC, thebigbone commented on cyctl/cmd/apply.go
> +func applyYaml(yamlFile []byte, config *rest.Config, telemetry bool) error {
done

2024-07-17 12:18 UTC, petar-cvit approved these changes
Thanks @thebigbone 🧡

2024-07-17 12:19 UTC, merged