Fix rollback rendering
cyclops-ui/cyclops pull request #442
Opened 2024-07-18 12:35 UTC by priyanshuverma-dev

closes #420

## 📑 Description
Fixed absence of module name in rollback helm render by passing the value of module name to renderer.

## ✅ Checks
- [ ] I have updated the documentation as required
- [x] I have performed a self-review of my code

## ℹ Additional context
![fixed](https://github.com/user-attachments/assets/c16c749a-a3db-4822-85c4-a4de376b1e8e)

2024-07-18 13:01 UTC, petar-cvit requested changes

2024-07-18 13:08 UTC, priyanshuverma-dev commented on cyclops-ctrl/internal/controller/modules.go
> +	var name string
Let me fix

2024-07-19 16:01 UTC, priyanshuverma-dev commented
It is the gentle reminder to review the PR @petar-cvit .

2024-07-19 18:55 UTC, petar-cvit approved these changes
Thanks @priyanshuverma-dev 🧡

2024-07-19 18:55 UTC, merged