Link to template
cyclops-ui/cyclops pull request #448
Opened 2024-07-18 16:15 UTC by tanbirali

closes #366 

## 📑 Description

## ✅ Checks
- [ ] I have updated the documentation as required
- [x] I have performed a self-review of my code

## ℹ Additional context
I have created a function to check if the template ref is not github template ref or not. If not a github template ref then only no link is generated.

2024-07-18 17:05 UTC, petar-cvit commented
Hey @tanbirali, can we make the link grey if the edit template is locked? Also, could you make the link underlined if you hover over it?

2024-07-18 17:35 UTC, tanbirali commented
Please have a look and let me know if this will work

2024-07-19 08:51 UTC, petar-cvit requested changes
Hey @tanbirali, left two comments

2024-07-19 08:51 UTC, petar-cvit commented on cyclops-ui/src/components/pages/EditModule/EditModule.tsx
> +          style={{ color: templateRefLock ? "gray" : "" }}
Can you replace gray with `#B8B8B8`

2024-07-19 08:51 UTC, petar-cvit commented on cyclops-ui/src/components/pages/EditModule/custom.css
> +}
This will make all `<a>` be underlined when hovered. Can you make a separate class and add text decoration to it?

2024-07-19 18:44 UTC, petar-cvit approved these changes
Thanks @tanbirali 🧡

2024-07-19 18:45 UTC, merged