fix(cyclops-ui): node card details added
cyclops-ui/cyclops pull request #473
Opened 2024-07-28 15:21 UTC by s-vamshi

closes #440

## 📑 Description

## ✅ Checks
- [ ] I have updated the documentation as required
- [x] I have performed a self-review of my code

## ℹ Additional context
added last transition time and heart beat time and message to the node conditions card
![image](https://github.com/user-attachments/assets/3ad6f453-074f-4ffa-8d1d-08707b2b907d)

2024-07-29 01:55 UTC, s-vamshi commented
@petar-cvit can you please review this PR?

2024-07-29 09:49 UTC, s-vamshi commented
@petar-cvit can please review this PR in your free time?

2024-07-29 15:18 UTC, petar-cvit requested changes

2024-07-29 15:18 UTC, petar-cvit commented on cyclops-ui/src/components/pages/NodeDetails.tsx
> +                  </code>
Can you replace `<code>` with `<Text code>` from ant design?

2024-07-29 16:18 UTC, s-vamshi commented
done @petar-cvit, can you please review now?

2024-07-29 16:49 UTC, s-vamshi commented
squashed all commits

2024-07-30 10:02 UTC, petar-cvit commented
Can you move the timestamps and the message in the next row
<img width="1285" alt="Screenshot 2024-07-30 at 12 02 10" src="https://github.com/user-attachments/assets/a773cb69-e06c-4b17-9e33-8cc9ce1ee2e9">

2024-07-30 10:58 UTC, s-vamshi commented
@petar-cvit made changes can you please review now?

2024-07-30 13:11 UTC, petar-cvit approved these changes
Thanks @s-vamshi 🧡

2024-07-30 13:12 UTC, merged