feat: Add loading state for template in EditModule and NewModule components
cyclops-ui/cyclops pull request #478
Opened 2024-07-30 03:35 UTC by ChiragAgg5k

closes #423 

## 📑 Description

Disables the `save` and `load values from file` buttons when a template is loading. also, it Disables changing of template when a template is loading.

## ✅ Checks
- [x] I have updated the documentation as required
- [x] I have performed a self-review of my code

2024-07-30 09:24 UTC, petar-cvit requested changes
@ChiragAgg5k thanks for the PR. Left one comment on reusing existing state we have in edit module

2024-07-30 09:24 UTC, petar-cvit commented on cyclops-ui/src/components/pages/EditModule/EditModule.tsx
Can we use existing `loadTemplate` instead of adding a new variable `isTemplateLoading`? `loadTemplate` indicates if a template has been loaded, so if it's false, it means the template is still loading.

2024-07-30 10:32 UTC, ChiragAgg5k commented on cyclops-ui/src/components/pages/EditModule/EditModule.tsx
Oh, sorry for the oversight. I will make the changes accordingly

2024-07-30 13:32 UTC, petar-cvit requested changes

2024-07-30 13:32 UTC, petar-cvit commented on cyclops-ui/src/components/pages/NewModule/NewModule.tsx
> +                disabled={loadingTemplate}
Can you also disable the button if `loadingTemplateInitialValues` is set? This is set to true while Cyclops is fetching initial values from a template. You can do it for all buttons

2024-07-30 13:32 UTC, petar-cvit commented on cyclops-ui/src/components/pages/EditModule/EditModule.tsx
> +                  disabled={templateRefLock || !loadTemplate}
You should add this to the path input as well.

2024-07-30 13:54 UTC, petar-cvit requested changes

2024-07-30 13:54 UTC, petar-cvit commented on cyclops-ui/src/components/pages/NewModule/NewModule.tsx
> +                disabled={loadingTemplate}
@ChiragAgg5k, you will have to add loadingTemplateInitialValues to disabled as well.

2024-07-31 13:38 UTC, petar-cvit approved these changes
Thanks @ChiragAgg5k 🧡

2024-07-31 13:46 UTC, merged