Reconcilation command line
cyclops-ui/cyclops pull request #595
Opened 2024-09-29 13:48 UTC by Abiji-2020

closes #586 

## 📑 Description

created a function in Cobra and added in the root command running `cyctl reconcile <module name>` will reconcile the specified module;

## ✅ Checks
- [ ] I have tested my code (provide screenshots or screen recordings of a working solution)
- [ ] I have performed a self-review of my code

2024-09-29 17:50 UTC, petar-cvit requested changes
@Abiji-2020 thanks for the PR! Let a couple of comments on cli output, but looks good

2024-09-29 17:50 UTC, petar-cvit commented on cyctl/cmd/reconcile.go
> +	Long:    "Will reconcile the Module and update the current TimeStamp",
```suggestion
	Short:   "Trigger module reconciliation",
	Long:    "Trigger module reconciliation",
```

2024-09-29 17:50 UTC, petar-cvit commented on cyctl/cmd/reconcile.go
> +	fmt.Printf("successfully reconciled %v", moduleName)
```suggestion
	fmt.Printf("successfully triggered reconciliation for module: %v", moduleName)
```

2024-09-29 17:50 UTC, petar-cvit commented on cyctl/cmd/reconcile.go
> +	reconcileExample = `# Reconcile the Module
```suggestion
	reconcileExample = `# Reconcile a Module 
```

2024-09-30 13:25 UTC, Abiji-2020 commented on cyctl/cmd/reconcile.go
> +	reconcileExample = `# Reconcile the Module
Finished the requested changes

2024-09-30 13:26 UTC, Abiji-2020 commented
@petar-cvit  The requested changes on the outputs of the cli have been updated

2024-09-30 13:36 UTC, petar-cvit approved these changes
Thanks @Abiji-2020 🧡

2024-09-30 13:38 UTC, merged