feat(cyclops-ctrl): adds prometheus metrics to reconciler
cyclops-ui/cyclops pull request #609
Opened 2024-10-04 17:02 UTC by naineel1209

closes #598

## 📑 Description
- added required reconciler metrics to the Prometheus monitor
- currently added metrics are 
```go
type Monitor struct {
	ModulesDeployed  prometheus.Gauge
	CacheHits        prometheus.Gauge
	CacheMisses      prometheus.Gauge
	CacheKeysAdded   prometheus.Gauge
	CacheCostAdded   prometheus.Gauge
	CacheKeysEvicted prometheus.Gauge
	CacheCostEvicted prometheus.Gauge

	// Reconciler Metrics
	ReconcilerDuration   prometheus.Histogram
	NoOfReconciliations   prometheus.Counter
	FailedReconciliations prometheus.Counter
}
```
- added methods to update the reconciler metrics
- added increment for `no_of_reconciliations` for every attempted reconciliation
- added increment for `failed_reconciliations` for every failed reconciliation
- added deferred function call to observe the amount of time spent in reconciliation 

## ✅ Checks
- [✅] I have tested my code (provide screenshots or screen recordings of a working solution)
- [✅] I have performed a self-review of my code

## ℹ Additional context

2024-10-04 17:03 UTC, naineel1209 commented
@quest-bot loot #598

2024-10-06 09:58 UTC, petar-cvit requested changes
Left a couple of comments on naming, but looks good

2024-10-06 09:58 UTC, petar-cvit commented on cyclops-ctrl/internal/prometheus/handler.go
> +	FailedReconciliations prometheus.Counter
Can you rename to:
```suggestion
	ReconciliationDuration   prometheus.Histogram
	ReconciliationCounter   prometheus.Counter
	FailedReconciliationCounter prometheus.Counter
```

2024-10-06 09:58 UTC, petar-cvit commented on cyclops-ctrl/internal/prometheus/handler.go
> +func (m *Monitor) IncNoOfReconciliations() {
Rename to `OnReconciliation`

2024-10-06 09:58 UTC, petar-cvit commented on cyclops-ctrl/internal/prometheus/handler.go
> +func (m *Monitor) IncFailedReconciliations() {
Rename to `OnFailedReconciliation`

2024-10-06 09:58 UTC, petar-cvit commented on cyclops-ctrl/internal/prometheus/handler.go
> +func (m *Monitor) ObserveReconcilerDuration(duration float64) {
Rename to `ObserveReconciliationDuration `

2024-10-10 10:12 UTC, petar-cvit approved these changes
Thanks @naineel1209 🧡

2024-10-10 10:12 UTC, merged