Add Toggle for NewModule Form and skipCRDs Support in Backend
cyclops-ui/cyclops pull request #616
Opened 2024-10-07 13:37 UTC by kom-senapati

closes #602 
@quest-bot loot #602

## 📑 Description
- Added support for the skipCRDs option in the backend reconciliation logic.
- Added a toggle switch for the skipCRDs option in the frontend NewModule form.

## ✅ Checks
- [X] I have tested my code (provide screenshots or screen recordings of a working solution)
- [X] I have performed a self-review of my code

## Screenshots

![image](https://github.com/user-attachments/assets/9bcc9bf5-e6bd-4387-840b-947511a1d54f)

2024-10-07 13:39 UTC, kom-senapati commented
@quest-bot loot #602

2024-10-13 15:52 UTC, petar-cvit requested changes
The skip crds values from the UI is not properly passed when creating a module and is never applied.

Also, since you are changing the CRD, run `make manifests` to generate manifests in `cyclops-ctrl/config/crd/bases`, and make sure the value is properly mapped in the kubernetes cluster

2024-10-13 15:52 UTC, petar-cvit commented on cyclops-ui/src/components/pages/NewModule/NewModule.tsx
> +                    name="skipCRDs"
Rname to `cyclops_module_skip_crds`

2024-10-17 13:19 UTC, kom-senapati commented on cyclops-ui/src/components/pages/NewModule/NewModule.tsx
> +                    name="skipCRDs"
Renamed

2024-10-17 13:22 UTC, kom-senapati commented
@petar-cvit Can you tell me the changes required in the backend

2024-10-17 13:27 UTC, kom-senapati commented
```sh
$ make manifests
make: *** No rule to make target 'manifests'.  Stop.
```

It's giving this output when running inside the `cyclops-ctrl/config/crd/bases` directory.

2024-12-24 11:22 UTC, closed without merging