feat(cyclops-ui): Copy Module Name and Namespace buttons
cyclops-ui/cyclops pull request #645
Opened 2024-10-21 14:48 UTC by ArnavK-09

closes #639

## 📑 Description

![image](https://github.com/user-attachments/assets/50236a82-082f-4f8f-b59f-27bb445288b6)

## ✅ Checks
- [x] I have tested my code (provide screenshots or screen recordings of a working solution)
- [x] I have performed a self-review of my code

## ℹ Additional context

2024-10-21 14:48 UTC, ArnavK-09 commented
@quest-bot loot #639

2024-10-22 11:08 UTC, KaradzaJuraj requested changes
Hey @ArnavK-09, the icons are currently positioned at the bottom, but I'd like them to be positioned at the top.

You will probably need to change the styling of the `<Title>` to use `flex` for the module name copy. For the namespace copy, you can update the styling of the `Description.Item`

Also, color the icons grey!

2024-10-22 11:08 UTC, KaradzaJuraj commented on cyclops-ui/src/components/pages/ModuleDetails.tsx
> +                  style={{
Color the icon grey

2024-10-22 11:08 UTC, KaradzaJuraj commented on cyclops-ui/src/components/pages/ModuleDetails.tsx
> +                  <CopyOutlined
Color the icon grey

2024-10-23 16:51 UTC, ArnavK-09 commented
> Hey @ArnavK-09, the icons are currently positioned at the bottom, but I'd like them to be positioned at the top.
> 
> You will probably need to change the styling of the `<Title>` to use `flex` for the module name copy. For the namespace copy, you can update the styling of the `Description.Item`
> 
> Also, color the icons grey!

"top"

![image](https://github.com/user-attachments/assets/2c10983f-6e8a-4248-824b-7391177afadd)

2024-10-23 18:44 UTC, KaradzaJuraj requested changes
Hey @ArnavK-09 , sorry for doing this but I dislike this solution (my fault, I proposed it).

I think a better solution would be if just by clicking on the module name (or namespace), it copies it to your clipboard.

I propose the following:
1) Remove the added buttons and styling
2) Wrap `{module.name}` & `{module.targetNamespace}` in `<span>` with the `OnClick` effect of copying + style the cursor when hovering to "pointer"
3) Wrap the new `<span>` with the `<Tooltip>` component so that when people hover over the name/namespace, a tooltip will appear to tell them they can copy it
4) update the tooltip text to "Copy module name to clipboard" and "Copy namespace to clipboard"

Let me know if this makes sense.

2024-10-23 18:51 UTC, ArnavK-09 commented
> Hey @ArnavK-09 , sorry for doing this but I dislike this solution (my fault, I proposed it).
> 
> I think a better solution would be if just by clicking on the module name (or namespace), it copies it to your clipboard.
> 
> I propose the following:
> 1) Remove the added buttons and styling
> 2) Wrap `{module.name}` & `{module.targetNamespace}` in `<span>` with the `OnClick` effect of copying + style the cursor when hovering to "pointer"
> 3) Wrap the new `<span>` with the `<Tooltip>` component so that when people hover over the name/namespace, a tooltip will appear to tell them they can copy it
> 4) update the tooltip text to "Copy module name to clipboard" and "Copy namespace to clipboard"
> 
> Let me know if this makes sense.

Yup, this looks better, 
I'll implement this asap and resolve this issue 
Thanks

2024-10-24 19:28 UTC, ArnavK-09 commented
> Hey @ArnavK-09 , sorry for doing this but I dislike this solution (my fault, I proposed it).
> 
> I think a better solution would be if just by clicking on the module name (or namespace), it copies it to your clipboard.
> 
> I propose the following:
> 1) Remove the added buttons and styling
> 2) Wrap `{module.name}` & `{module.targetNamespace}` in `<span>` with the `OnClick` effect of copying + style the cursor when hovering to "pointer"
> 3) Wrap the new `<span>` with the `<Tooltip>` component so that when people hover over the name/namespace, a tooltip will appear to tell them they can copy it
> 4) update the tooltip text to "Copy module name to clipboard" and "Copy namespace to clipboard"
> 
> Let me know if this makes sense.

Like this?

2024-10-25 18:02 UTC, ArnavK-09 commented
> Just a small change to finish this off 😅

sure, is this alr?

2024-10-27 14:26 UTC, KaradzaJuraj approved these changes
Looking good! Thanks @ArnavK-09 🙏

2024-10-27 15:36 UTC, merged